#!/bin/bash
#
# description: GOD monitors daemons
#              
### BEGIN INIT INFO
# Provides:          god
# Required-Start:    $prestart
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
. /lib/lsb/init-functions

PATH=/sbin:/bin:/usr/sbin:/usr/bin
NAME=god
DESC="GOD monitors daemons"
DIR=/usr/bin
DAEMON=$DIR/$NAME
CONFIGFILEDIR=/home/pcockrell/www/ria/god
PIDFILE=/var/run/$NAME/$NAME.pid
LOGFILE=/var/log/$NAME.log

#DEBUG_OPTIONS="--log-level debug"
DEBUG_OPTIONS=""


# Gracefully exit if 'god' gem is not available.
test -x $DAEMON || exit 

#
#if ! [ -x $DAEMON ];then
#  echo "ERROR - Can't find $DAEMON"
#  exit 1 
#fi
#
#if [ $UID -gt 0 ]; then
#  echo "ERROR - must run as root"
#  exit 1
#fi
#
#cd $DIR
#
#case "$1" in
#  start)
#        log_daemon_msg "Starting $DESC"
#        start-stop-daemon --start --pidfile $PIDFILE --quiet --startas $DAEMON -- $DAEMON_OPTS
#        for file in `ls -1 $CONFIGFILEDIR/*.god`; do $DAEMON load $file; done
#        RETVAL=$?
#        log_end_msg $RETVAL
#        ;;
#    stop)
#        log_daemon_msg "Stopping $DESC"      
#        #god terminate
#        #start-stop-daemon -R TERM/15/KILL/5 --stop --quiet --pidfile $PIDFILE
#        start-stop-daemon --stop --quiet --oknodo -m --pidfile $PIDFILE
#        rm -f $PIDFILE
#        RETVAL=$?
#        log_end_msg $RETVAL
#        ;;
#    restart)
#        log_daemon_msg "Restarting $DESC"
#        start-stop-daemon -R TERM/15/KILL/5 --stop --quiet --pidfile $PIDFILE
#        rm -f $PIDFILE
#        RETVAL=$?
#        log_end_msg $RETVAL
#        sleep 5
#        start-stop-daemon --start --pidfile $PIDFILE --quiet --startas $DAEMON -- $DAEMON_OPTS
#        RETVAL=$?
#        log_end_msg $RETVAL
#        ;;
#    status)
#        echo -n "Status of $DESC: "
#        if [ ! -r "$PIDFILE" ]; then
#            echo "$NAME is not running."
#            exit 3
#        fi
#        if read pid < "$PIDFILE" && ps -p "$pid" > /dev/null 2>&1; then
#            echo "$NAME is running - $pid."
#            exit 0
#        else
#            echo "$NAME is not running but $PIDFILE exists."
#            exit 1
#        fi
#        ;;
#    *)
#      echo "Usage: $0 {start|stop|restart|status}"
#      exit 1
#      ;;
#esac      
#
#exit $RETVAL

RETVAL=0

god_start() {
  start_cmd="$DAEMON -l $LOGFILE -P $PIDFILE $DEBUG_OPTIONS"
  echo $start_cmd
  $start_cmd || echo -en "god already running"
  RETVAL=$?
  if [ "$RETVAL" == '0' ]; then
    sleep 2 # wait for server to load before loading config files
    if [ -d $CONFIGFILEDIR ]; then
      for file in `ls -1 $CONFIGFILEDIR/*.god`; do
        echo "god: loading $file ..."
        $DAEMON load $file
      done
    fi
  fi
  return $RETVAL
}

god_stop() {
  stop_cmd="god terminate"
  echo $stop_cmd
  $stop_cmd || echo -en "god not running"
}

case "$1" in
  start)
    god_start
    RETVAL=$?
    ;;
  stop)
    god_stop
    RETVAL=$?
    ;;
  restart)
    god_stop
    god_start
    RETVAL=$?
    ;;
  status)
    $DAEMON status
    RETVAL=$?
    ;;
  *)
    echo "Usage: god {start|stop|restart|status}"
    exit 1
    ;;
esac

exit $RETVAL
